core/urls.py
from django.urls import path 
from  . import views 
from core.views import (Product_view, SnippetList, Leads_view, Emailopp_view, Emailsamplelead_view, Emailbenchsales_view, CustomEmailleads_view, CustomBenchsales_view, CustomEmailleadsopportunities_view, whatsappcareersales_view, whatsappbenchsales_view, DuplicatedCustomEmailleadsView,Duplicatedwhatsappcareersales_view)

from django.urls import re_path
urlpatterns = [
    path('index/',views.index, name='index'),
    path('getDatapoint/',views.getDatapoint, name='getDatapoint'),
    path('upload/', views.upload_txt, name='upload_txt'),
    path('emailleadupload/', views.emaillead_upload_txt, name='emailleadupload'),
    path('emailbenchsalesupload/', views.emailbenchsalesupload, name='emailbenchsalesupload'),
    path('emailbenchsalesupdate/<int:id>',views.benchsalesupdate,name="emailbenchsalesupdate"),
    path('emailbenchsalesedit/<int:id>',views.emailbenchsalesedit,name="emailbenchsalesedit"),
    path('benchsales/', Emailbenchsales_view.as_view(), name="benchsales"),
    #cutom email leads
    path('customemailleadsupdate/<int:id>',views.customemailleadsupdate,name="customemailleadsupdate"),
    path('customemailleadsview/<int:id>',views.customemailleadsedit,name="customemailleadsview"),
    path('customemailleads/',CustomEmailleads_view.as_view(),name="customemailleads"),
    path('customemailleadscreate/', views.Customemailleadscreate, name="customemailleadscreate"),
    path('customemailleadsedits/<int:id>', views.customemailleadsedits, name="customemailleadsedits"),
    path('customemailleadcontent/<int:id>', views.customemailleadcontent, name="customemailleadcontent"),
    path('customemailleadsupdateadd/<int:id>', views.customemailleadsupdateadd, name="customemailleadsupdateadd"),
    # custom email leads oppurtunties
    path('customemailleadsopportunities/',CustomEmailleadsopportunities_view.as_view(),name="customemailleadsopportunities"),
    path('customleadopportunitiesview/<int:id>', views.customleadopportunitiesview, name="customleadopportunitiesview"),

    # custom email bench sales 
    path('custombenchsalesedits/<int:id>',views.custombenchsalesedits, name="custombenchsalesedits" ),
    path('custombenchsalesupdateadd/<int:id>', views.custombenchsalesupdateadd, name="custombenchsalesupdateadd"),

    path('custombenchsalescontent/<int:id>', views.custombenchsalescontent, name="custombenchsalescontent"),
    path('custombenchsalesupdate/<int:id>',views.custombenchsalesupdate,name="custombenchsalesupdate"),
    path('custombenchsalesview/<int:id>',views.custombenchsalesedit,name="custombenchsalesview"),
    path('custombenchsales/',CustomBenchsales_view.as_view(),name="custombenchsales"),
    path('Custombenchsalescreate/', views.Custombenchsalescreate, name="Custombenchsalescreate"),
    
    path('custombenchsalesadd/', views.custombenchsalesadd, name="custombenchsalesadd"),
    # path('', views.upload_txt, name='upload_txt'),
    # path('retrieve/',views.retrieve,name="retrieve"),
    path('edit/<int:id>',views.edit,name="edit"),
    path('leadedit/<int:id>',views.leadedit,name="leadedit"),
    path('emailnewleadsedit/<int:id>',views.emailsampleleadedit,name="emailnewleadsedit"),
    # path('emailleadedit/<int:id>',views.emailleadedit,name="emailleadedit"),
    path('emailleadoppurtunitiesedit/<int:id>',views.emailleadoppurtunitiesedit,name="emailleadoppurtunitiesedit"),
    path('update/<int:id>',views.update,name="update"),
    path('emailnewleadsupdate/<int:id>',views.sampleleadupdate,name="emailnewleadsupdate"),
    # path('emailleadupdate/<int:id>',views.emailleadupdate,name="emailleadupdate"),
    path('emailleadoppupdate/<int:id>',views.emailleadoppupdate,name="emailleadoppupdate"),
    path('leadupdate/<int:id>',views.leadupdate,name="leadupdate"),
    # path('leadupdate/<int:id>',views.emailleadoppupdate,name="leadupdate"),
    path('delete/<int:id>',views.delete,name="delete"),
    path('opportunities/',views.search, name="search"),
    path('', Product_view.as_view(), name="home"),
    # path('emailhome/', Emailproduct_view.as_view(), name="emailhome"),
    path('emailleadoppurtunities/', Emailopp_view.as_view(), name="emailleadoppurtunities"),
    path('emailnewleads/', Emailsamplelead_view.as_view(), name="emailnewleads"),
    path('retrieve/', Product_view.as_view(), name="retrieve"),
    path('leads/', Leads_view.as_view(), name="leads"),
    #whatsapp career sales
    path('whatsupcareersalesview/<int:id>',views.whatsappcareersalesview,name="whatsupcareersalesview"),
    path('whatsupcareersales/', whatsappcareersales_view.as_view(), name="whatsupcareersales"),
    path('whatsupcareersalesedit/<int:id>', views.whatsappcareersalesedit, name="whatsupcareersalesedit"),
    path('whatsupcareersalescreate/', views.whatsappcareersalescreate, name="whatsupcareersalescreate"),
    #whatsapp bench sales
    path('whatsupbenchsalesview/<int:id>',views.whatsappbenchsalesview,name="whatsupbenchsalesview"),
    path('whatsupbenchsales/', whatsappbenchsales_view.as_view(), name="whatsupbenchsales"),
    path('whatsupbenchsalesedit/<int:id>', views.whatsappbenchsalesedit, name="whatsupbenchsalesedit"),
    path('whatsupbenchsalescreate/', views.whatsappbenchsalescreate, name="whatsupbenchsalescreate"),
    path('status/<int:id>/', views.status, name='status'),
    re_path(r'snippets/$', SnippetList.as_view(), name='snippet-list'),
    path('snippets/', SnippetList.as_view(), name="snippet"),
    path('customemailleadsfile/', views.customemailleadsfile, name='customemailleadsfile'),
    path('custombenchsalesfile/', views.custombenchsalesfile, name='custombenchsalesfile'),
    # path('locations/', views.locations, name="locations"),
    path('duplicatefilm/<int:id>/', views.duplicate_film, name='duplicatefilm'),
    path('emailduplicatefilm/<int:id>/', views.emailduplicate_film, name='emailduplicatefilm'),
    path('whatsappbenchsalescontent/<int:id>', views.whatsappbenchsalescontent, name="whatsappbenchsalescontent"),
    path('whatappspam/<str:string_param>/', views.spamremovals_testing, name="whatappspam"),
    path('whatappcareersales/<str:string_param>/', views.careersales_testing, name="whatappcareersales"),
    path('whatappbenchsales/<str:string_param>/', views.benchsales_testing, name="whatappbenchsales"),
    path('duplicated_emailleads/<int:id>/', DuplicatedCustomEmailleadsView.as_view(), name='duplicated_customemailleadsview'),
    path('whatsupduplicated_emailleads/<int:id>/', Duplicatedwhatsappcareersales_view.as_view(), name='duplicated_whatsupleadsview'),
    path('alias/',views.alias,name="alias"),
        
]

mysite/urls.py
from django.contrib import admin
from django.urls import  include, path
from django.conf import settings
from django.conf.urls.static import static
from core import views

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('chatgpt/', include('chatgpt.urls')),
    path('email/', include('mail.urls')),
    path('resume/', include('resume.urls')),
    path('contents/', include('contents.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path("", views.index, name="index"),
    path('resumeupload/', views.upload_and_extract_resume, name='resumeupload'),
    path('success/', views.success_view, name='success_view'),
    path('extracted_resumes/', views.extracted_resume_list, name='extracted_resumes'),
    path('extracted_resumes/edit/<int:pk>', views.edit_extracted_resume, name='edit_extracted_resume'),
    path('extracted_resumes/delete/<int:pk>', views.delete_extracted_resume, name='delete_extracted_resume'),

    path('extracted_resumes/profile/<int:pk>', views.update_profile, name='profile'),
    path('extracted_resumes/objective/<int:pk>', views.update_objective, name='objective'),
    path('extracted_resumes/professional/<int:pk>', views.update_professional, name='professional'),
    path('extracted_resumes/education/<int:pk>', views.update_education, name='education'),
    path('extracted_resumes/skill/<int:pk>', views.update_skill, name='skill'),
    path('extracted_resumes/experience/<int:pk>', views.update_experience, name='experience'),
    path('extracted_resumes/reference/<int:pk>', views.update_reference, name='reference'),
    path('extracted_resumes/certificate/<int:pk>', views.update_certificate, name='certificate'),
    path('extracted_resumes/award/<int:pk>', views.update_award, name='award'),
    path('extracted_resumes/hobbies/<int:pk>', views.update_hobbies, name='hobbies'),

    path('extracted_resumes/addexperience/<int:pk>', views.add_candidate_experience, name='add_candidate_experience'),
    path('extracted_resumes/add/<int:pk>', views.add, name='add'),
    path('extracted_resumes/addeducation/<int:pk>', views.add_education, name='addeducation'),
    path('extracted_resumes/addreference/<int:pk>', views.add_reference, name='addreference'),
    path('extracted_resumes/addcertificate/<int:pk>', views.add_certificate, name='addcertificate'),
    path('extracted_resumes/addaward/<int:pk>', views.add_award, name='addaward'),
    path('extracted_resumes/addhobbies/<int:pk>', views.add_hobbies, name='addhobbies'),

    path('extracted_resumes/skillsdelete/<int:pk>', views.delete_skills_resume, name='delete_skills_resume'),
    path('extracted_resumes/educationdelete/<int:pk>', views.delete_education_resume, name='delete_education_resume'),
    path('extracted_resumes/experiencedelete/<int:pk>', views.delete_experience_resume, name='delete_experience_resume'),
    path('extracted_resumes/referencedelete/<int:pk>', views.delete_reference_resume, name='delete_reference_resume'),
    path('extracted_resumes/certificatedelete/<int:pk>', views.delete_certificate_resume, name='delete_certificate_resume'),
    path('extracted_resumes/awarddelete/<int:pk>', views.delete_award_resume, name='delete_award_resume'),
    path('extracted_resumes/hobbiesdelete/<int:pk>', views.delete_hobbies_resume, name='delete_hobbies_resume'),

    path('extracted_resumes/editskills/<int:pk>', views.edit_candidateskill, name='edit_candidateskill'),
    path('extracted_resumes/get_edit_screen_skills_experience', views.get_edit_screen_skills_experience, name='get_edit_screen_skills_experience'),
    path('extracted_resumes/edit_skills_experience/<int:pk>', views.edit_skills_experience, name='edit_skills_experience'),
    path('extracted_resumes/get_edit_screen_education', views.get_edit_screen_education, name='get_edit_screen_education'),
    path('extracted_resumes/edit_education/<int:pk>', views.edit_education, name='edit_education'),
    path('extracted_resumes/get_edit_screen__by_email', views.get_edit_screen__by_email, name='get_edit_screen__by_email'),
    path('extracted_resumes/edit_by_email/<int:pk>', views.edit_by_email, name='edit_by_email'),
    path('extracted_resumes/get_edit_screen_experience', views.get_edit_screen_experience, name='get_edit_screen_experience'),
    path('extracted_resumes/edit_experience/<int:pk>', views.edit_experience, name='edit_experience'),

    path('extracted_resumes/get_edit_screen_certificate', views.get_edit_screen_certificate, name='get_edit_screen_certificate'),
    path('extracted_resumes/edit_certificate_code/<int:pk>', views.edit_certificate_code, name='edit_certificate_code'),

    path('extracted_resumes/get_edit_screen_award', views.get_edit_screen_award, name='get_edit_screen_award'),
    path('extracted_resumes/edit_award/<int:pk>', views.edit_award, name='edit_award'),

    path('extracted_resumes/get_edit_screen_hobbies', views.get_edit_screen_hobbies, name='get_edit_screen_hobbies'),
    path('extracted_resumes/edit_hobbies/<int:pk>', views.edit_hobbies, name='edit_hobbies'),

    path('extracted_resumes/get_edit_screen_job_skills', views.get_edit_screen_job_skills, name='get_edit_screen_job_skills'),
    path('extracted_resumes/edit_skills_used/<int:pk>', views.edit_skills_used, name='edit_skills_used'),
    path('extracted_resumes/update_or_create/<int:pk>', views.edit_by_candidatereparser, name='update_or_create'),
]


resume/models.py
from django.db import models


class Resume(models.Model):
    file = models.FileField(upload_to='resumes/')
  
    def __str__(self):
        # return self.file.name
        return str(self.id)


class candidateprofile(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)
    resumetext = models.TextField( blank=True)
    name = models.CharField(max_length=255,blank=True)
    lastname = models.CharField(max_length=255,blank=True)
    contact_number = models.CharField(max_length=255,blank=True)
    phone_carrier = models.CharField(max_length=255,blank=True)
    email = models.EmailField(max_length=255, blank=True)
    total_experience = models.TextField(blank=True)
    category = models.TextField(blank=True)
    education =models.TextField(blank=True)
    specialization = models.TextField(blank=True)
    legalstatus = models.CharField(max_length=255,blank=True)
    password = models.TextField(blank=True)
    address = models.TextField(blank=True)
    city = models.CharField(max_length=255,blank=True)
    state = models.CharField(max_length=255,blank=True)
    zipcode = models.CharField(max_length=255,blank=True)

    def __str__(self, *args, **kwargs):
        return self.name or str(self.id)

class candidateobjective(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)   
    objectives = models.TextField(blank=True)

    def __str__(self, *args, **kwargs):
        return self.objectives or str(self.id)

class candidateprofessional(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)    
    professional_summary = models.TextField(blank=True)

    def __str__(self, *args, **kwargs):
        return self.professional_summary or str(self.id)
        
class candidateeducation(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)   
    degree = models.TextField(blank=True)
    majordegree = models.TextField(blank=True)
    specializationdegree = models.TextField(blank=True)
    institute = models.TextField(blank=True)
    start_year = models.TextField(blank=True)
    end_year = models.TextField(blank=True)
    institutelocation = models.TextField(blank=True)
    others = models.TextField(blank=True)
    if_others = models.TextField(blank=True)

    def __str__(self, *args, **kwargs):
        return self.degree or str(self.id)

class candidateskill(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)   
    skills = models.TextField(blank=True)
    experience = models.TextField(blank=True)

    def __str__(self, *args, **kwargs):
        return self.skills or str(self.id)

class candidateexperience(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)   
    companyname = models.TextField(blank=True)
    job_title = models.TextField(blank=True)
    joblocation = models.TextField(blank=True)
    job_start_year = models.TextField(null=True,blank=True)
    job_end_year = models.TextField(null=True,blank=True)
    job_start_month = models.TextField(null=True,blank=True)
    job_end_month = models.TextField(null=True,blank=True)
    present = models.TextField(null=True,blank=True)
    # present = models.BooleanField(default=False)
    Description = models.TextField(blank=True)
    Responsibilites = models.TextField(blank=True)
    Accomplishments = models.TextField(blank=True)
    skillused = models.TextField(blank=True)

    def __str__(self, args, *kwargs):
        return self.companyname or str(self.id)
    
class candidatereference(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)   
    referred_by = models.TextField(blank=True)
    referrer_email = models.TextField(blank=True)

    def __str__(self, args, *kwargs):
        return self.referred_by or str(self.id) 
    
class candidatecertificate(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)   
    Certification_code = models.TextField(blank=True)
    certification_name = models.TextField(blank=True)
    date_of_certification = models.TextField(blank=True)

    def __str__(self, args, *kwargs):
        return self.Certification_code or str(self.id) 
    
class candidateaward(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)   
    award = models.TextField(blank=True)

    def __str__(self, args, *kwargs):
        return self.award or str(self.id)
    
class candidatehobbies(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)   
    hobbies= models.TextField(blank=True)

    def __str__(self, args, *kwargs):
        return self.hobbies or str(self.id) 
    


class candidatereparser(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)   
    ResumeParser= models.TextField(blank=True)
    ExperienceParser= models.TextField(blank=True)
    EducationParser = models.TextField(blank=True)
    CertificateParser = models.TextField(blank=True)
    
    def __str__(self, args, *kwargs):
        return self.resume or str(self.id) 

templates/resume/add_candidate_education.html
<!DOCTYPE html>
<html>
    <style>
        .back {
        padding: 10px 20px;
        background: #9b0b0b;
        color: #fff;
        text-decoration: none;
        border-radius: 20px;
        font-size: 15px;
      }
      .next {
        padding: 10px 20px;
        background: #0b9b3f;
        color: #fff;
        text-decoration: none;
        border-radius: 20px;
        font-size: 15px;
      }
    </style>
    <head>
<title>
    Add Education
</title>
    </head>
    <body>
        <h1>
            Add Candidate Education
        </h1>
        <form method="POST" action="/resume/extracted_resumes/addeducation/{{candidateeducation.id}}">
            {% csrf_token %}
        <!-- <label type="hidden"  for="resume">Skills:</label> -->
        <input  type="hidden" name="resume" id="resume" rows="4" cols="50" value="{{candidateeducation.id}}">
             <!-- Skills -->

        <label for="institute">Institution:</label>
        <textarea name="institute" id="institute" rows="4" cols="50" required></textarea><br><br>

        <label for="start_year">From:</label>
        <textarea name="start_year" id="start_year" rows="4" cols="50" required></textarea><br><br>

        <label for="end_year">To:</label>
        <textarea name="end_year" id="end_year" rows="4" cols="50" required></textarea><br><br>

        <label for="degree">Qualification:</label>
        <textarea name="degree" id="degree" rows="4" cols="50" required></textarea><br><br>

        <!-- Experience -->
        <label for="majordegree">Major:</label>
        <textarea name="majordegree" id="majordegree" rows="4" cols="50" required></textarea><br><br>

        <label for="specializationdegree">Specialization:</label>
        <textarea name="specializationdegree" id="specializationdegree" rows="4" cols="50" required></textarea><br><br>

        <label for="others">Others:</label>
        <textarea name="others" id="others" rows="4" cols="50" required></textarea><br><br>

        <label for="if_others">If Others:</label>
        <textarea name="if_others" id="if_others" rows="4" cols="50" required></textarea><br><br>

        <label for="institutelocation">Place :</label>
        <textarea name="institutelocation" id="institutelocation" rows="4" cols="50" required></textarea><br><br>

        <a class="back" href="{% url 'edit_extracted_resume' pk=candidateeducation.id %}">Cancel</a>

        <button class="next" type="submit">Submit</button>
        </form>
    </body>
</html>

templates/resume/add_candidate_experience.html
<!DOCTYPE html>
<html>
    <style>
        .back {
        padding: 10px 20px;
        background: #9b0b0b;
        color: #fff;
        text-decoration: none;
        border-radius: 20px;
        font-size: 15px;
      }
      .next {
        padding: 10px 20px;
        background: #0b9b3f;
        color: #fff;
        text-decoration: none;
        border-radius: 20px;
        font-size: 15px;
      }
    </style>
    <head>
<title>
    Add Experience
</title>
    </head>
    <body>
        <h1>
            Add Candidate Experience
        </h1>
        <form method="POST" action="/resume/extracted_resumes/addexperience/{{candidateexperience.id}}">
            {% csrf_token %}
        <!-- <label type="hidden"  for="resume">Skills:</label> -->
        <input  type="hidden" name="resume" id="resume" rows="4" cols="50" value="{{candidateexperience.id}}">

        <label for="companyname">Company Name:</label>
        <textarea name="companyname" id="companyname" rows="4" cols="50" required></textarea><br><br>

        <label for="job_title">Job Title:</label>
        <textarea name="job_title" id="job_title" rows="4" cols="50" required></textarea><br><br>

        <label for="skillused">Skills Used:</label>
        <textarea name="skillused" id="skillused" rows="4" cols="50" required></textarea><br><br>

        <label for="joblocation">Location:</label>
        <textarea name="joblocation" id="joblocation" rows="4" cols="50" required></textarea><br><br>

        <a class="back" href="{% url 'edit_extracted_resume' pk=candidateexperience.id %}">Cancel</a>

        <button class="next" type="submit">Submit</button>
        </form>
    </body>
</html>

templates/resume/add_candidate_skill.html
<!DOCTYPE html>
<html>
    <style>
        .back {
        padding: 10px 20px;
        background: #9b0b0b;
        color: #fff;
        text-decoration: none;
        border-radius: 20px;
        font-size: 15px;
      }
      .next {
        padding: 10px 20px;
        background: #0b9b3f;
        color: #fff;
        text-decoration: none;
        border-radius: 20px;
        font-size: 15px;
      }
    </style>
    <head>
<title>
    Add skills and experience
</title>
    </head>
    <body>
        <h1>
            Add Candidate Skill
        </h1>
        <form method="POST" action="/resume/extracted_resumes/addskills/{{candidateskill.id}}">
            {% csrf_token %}
        <!-- <label type="hidden"  for="resume">Skills:</label> -->
        <input  type="hidden" name="resume" id="resume" rows="4" cols="50" value="{{candidateskill.id}}">
             <!-- Skills -->
        <label for="skills">Skills:</label>
        <textarea name="skills" id="skills" rows="4" cols="50" required></textarea><br><br>

        <!-- Experience -->
        <label for="experience">Experience:</label>
        <textarea name="experience" id="experience" rows="4" cols="50" required></textarea><br><br>
        <a class="back" href="{% url 'edit_extracted_resume' pk=candidateskill.id %}">Cancel</a>

        <button class="next" type="submit">Submit</button>
        </form>
    </body>
</html>

templates/resume/add_item.html




<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Disable Closing of Bootstrap Modal on Click of Dark Area</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script>
$(document).ready(function(){
	$('.launch-modal').click(function(){
		$('#myModal').modal({
			backdrop: 'static'
		});
	}); 
});
</script>
<style>
    .bs-example{
    	margin: 20px;
    }
</style>
</head>
<body>
<div class="bs-example">
    <!-- Button HTML (to Trigger Modal) -->
    <input type="button" class="btn btn-lg btn-primary launch-modal" value="Launch Demo Modal">
    
    <!-- Modal HTML -->
    <div id="myModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">ADD Sillks</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <form method="post" action="{% url 'add_item' %}">
                    <div class="modal-body">
                        {% csrf_token %}
                        {{ candidateform.as_p }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
                <!-- <form method="post" action="/resume/extracted_resumes/skills/">
                    <div class="modal-body">
                        {% csrf_token %}

                    <p><label for="id_skills">Skills:</label> <textarea name="skills" cols="40" rows="10" id="id_skills"></textarea></p>
                    <p><label for="id_experience">Experience:</label> <textarea name="experience" cols="40" rows="10" id="id_experience"></textarea></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form> -->
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/resume/delete_resume.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Extracted Resume</title>
</head>
<body>
    <h1>Delete Extracted Resume</h1>
    <p>Are you sure you want to delete '{{ extracted_resume.name }}'?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm Delete</button>
        <a href="{% url 'extracted_resumes' %}">Cancel</a>
    </form>
    
</body>
</html>

templates/resume/editskills.html
<!DOCTYPE html>
<html>
    <style>
        .back {
        padding: 10px 20px;
        background: #9b0b0b;
        color: #fff;
        text-decoration: none;
        border-radius: 20px;
        font-size: 15px;
      }
      .next {
        padding: 10px 20px;
        background: #0b9b3f;
        color: #fff;
        text-decoration: none;
        border-radius: 20px;
        font-size: 15px;
      }
    </style>
    <head>
<title>
    Add skills and experience
</title>
    </head>
    <body>
        <h1>
            Add Candidate Skill
        </h1>
        <!-- <form method="POST" action="/resume/extracted_resumes/editskills/{{candidateskill_instance.resume_id}}"> -->
        <form method="post" action="{% url 'edit_candidateskill' pk=candidateskill_instance.pk %}">
            {% csrf_token %}
        <!-- <label type="hidden"  for="resume">Skills:</label> -->
        <input  type="hidden" name="resume" id="resume" rows="4" cols="50" value="{{candidateskill_instance.resume_id}}">
             <!-- Skills -->
        <label for="skills">Skills:</label>
        <textarea name="skills" id="skills" rows="4" cols="50" required>{{candidateskill_instance.skills}}</textarea><br><br>

        <!-- Experience -->
        <label for="experience">Experience:</label>
        <textarea name="experience" id="experience" rows="4" cols="50" required>{{candidateskill_instance.experience}}</textarea><br><br>
        
        <button class="next" type="submit">Submit</button>
        </form>
    </body>
</html>

templates/resume/success copy.html
<!DOCTYPE html>
<html>
<head>
    <title>Extracted Resume Data</title>
    <style>
        table, th, td {
          border: 1px solid black;
          border-collapse: collapse;
        }
        </style>
</head>
<body>
    <h1>Extracted Resume Data</h1>
    
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Contact Number</th>
                <th>Email</th>
                <th>Skills</th>
                <!-- <th>Education</th> -->
                <th>Degree</th>
                <th>College</th>
                <th>Years</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ extracted_data.name }}</td>
                <td>{{ extracted_data.contact_number }}</td>
                <td>{{ extracted_data.email }}</td>
                <td>
                    {% for skill in extracted_data.skills %}
                        {{ skill }}<br>
                    {% endfor %}
                </td>
                <td>
                    {{ extracted_data.degree }}
                </td>
                <td>
                    {{ extracted_data.college }}
                </td>
                <td>
                    {{ extracted_data.years }}
                </td>
            </tr>
        </tbody>
    </table>
</body>
</html>

    <!-- <h1>Extracted Resume Data</h1>
    
    <table border="1">
        <thead>
            <tr>
                <th>Name</th>
                <th>Contact Number</th>
                <th>Email</th>
                <th>Skills</th>
                <th>Education</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ extracted_data.name }}</td>
                <td>{{ extracted_data.contact_number }}</td>
                <td>{{ extracted_data.email }}</td>
                <td>
                    {% for skill in extracted_data.skills %}
                        {{ skill }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </td>
                <td>
                    {% for education in extracted_data.education %}
                        {{ education }}{% if not forloop.last %}<br>{% endif %}
                    {% endfor %}
                </td>
            </tr>
        </tbody>
    </table> -->
</body>
</html>