core/urls.py
from django.urls import path 
from  . import views 
from core.views import (Product_view, SnippetList, Leads_view, Emailopp_view, Emailsamplelead_view, Emailbenchsales_view, CustomEmailleads_view, CustomBenchsales_view, CustomEmailleadsopportunities_view, whatsappcareersales_view, whatsappbenchsales_view, DuplicatedCustomEmailleadsView,Duplicatedwhatsappcareersales_view)

from django.urls import re_path
urlpatterns = [
    path('index/',views.index, name='index'),
    path('getDatapoint/',views.getDatapoint, name='getDatapoint'),
    path('upload/', views.upload_txt, name='upload_txt'),
    path('emailleadupload/', views.emaillead_upload_txt, name='emailleadupload'),
    path('emailbenchsalesupload/', views.emailbenchsalesupload, name='emailbenchsalesupload'),
    path('emailbenchsalesupdate/<int:id>',views.benchsalesupdate,name="emailbenchsalesupdate"),
    path('emailbenchsalesedit/<int:id>',views.emailbenchsalesedit,name="emailbenchsalesedit"),
    path('benchsales/', Emailbenchsales_view.as_view(), name="benchsales"),
    #cutom email leads
    path('customemailleadsupdate/<int:id>',views.customemailleadsupdate,name="customemailleadsupdate"),
    path('customemailleadsview/<int:id>',views.customemailleadsedit,name="customemailleadsview"),
    path('customemailleads/',CustomEmailleads_view.as_view(),name="customemailleads"),
    path('customemailleadscreate/', views.Customemailleadscreate, name="customemailleadscreate"),
    path('customemailleadsedits/<int:id>', views.customemailleadsedits, name="customemailleadsedits"),
    path('customemailleadcontent/<int:id>', views.customemailleadcontent, name="customemailleadcontent"),
    path('customemailleadsupdateadd/<int:id>', views.customemailleadsupdateadd, name="customemailleadsupdateadd"),
    # custom email leads oppurtunties
    path('customemailleadsopportunities/',CustomEmailleadsopportunities_view.as_view(),name="customemailleadsopportunities"),
    path('customleadopportunitiesview/<int:id>', views.customleadopportunitiesview, name="customleadopportunitiesview"),

    # custom email bench sales 
    path('custombenchsalesedits/<int:id>',views.custombenchsalesedits, name="custombenchsalesedits" ),
    path('custombenchsalesupdateadd/<int:id>', views.custombenchsalesupdateadd, name="custombenchsalesupdateadd"),

    path('custombenchsalescontent/<int:id>', views.custombenchsalescontent, name="custombenchsalescontent"),
    path('custombenchsalesupdate/<int:id>',views.custombenchsalesupdate,name="custombenchsalesupdate"),
    path('custombenchsalesview/<int:id>',views.custombenchsalesedit,name="custombenchsalesview"),
    path('custombenchsales/',CustomBenchsales_view.as_view(),name="custombenchsales"),
    path('Custombenchsalescreate/', views.Custombenchsalescreate, name="Custombenchsalescreate"),
    
    path('custombenchsalesadd/', views.custombenchsalesadd, name="custombenchsalesadd"),
    # path('', views.upload_txt, name='upload_txt'),
    # path('retrieve/',views.retrieve,name="retrieve"),
    path('edit/<int:id>',views.edit,name="edit"),
    path('leadedit/<int:id>',views.leadedit,name="leadedit"),
    path('emailnewleadsedit/<int:id>',views.emailsampleleadedit,name="emailnewleadsedit"),
    # path('emailleadedit/<int:id>',views.emailleadedit,name="emailleadedit"),
    path('emailleadoppurtunitiesedit/<int:id>',views.emailleadoppurtunitiesedit,name="emailleadoppurtunitiesedit"),
    path('update/<int:id>',views.update,name="update"),
    path('emailnewleadsupdate/<int:id>',views.sampleleadupdate,name="emailnewleadsupdate"),
    # path('emailleadupdate/<int:id>',views.emailleadupdate,name="emailleadupdate"),
    path('emailleadoppupdate/<int:id>',views.emailleadoppupdate,name="emailleadoppupdate"),
    path('leadupdate/<int:id>',views.leadupdate,name="leadupdate"),
    # path('leadupdate/<int:id>',views.emailleadoppupdate,name="leadupdate"),
    path('delete/<int:id>',views.delete,name="delete"),
    path('opportunities/',views.search, name="search"),
    path('', Product_view.as_view(), name="home"),
    # path('emailhome/', Emailproduct_view.as_view(), name="emailhome"),
    path('emailleadoppurtunities/', Emailopp_view.as_view(), name="emailleadoppurtunities"),
    path('emailnewleads/', Emailsamplelead_view.as_view(), name="emailnewleads"),
    path('retrieve/', Product_view.as_view(), name="retrieve"),
    path('leads/', Leads_view.as_view(), name="leads"),
    #whatsapp career sales
    path('whatsupcareersalesview/<int:id>',views.whatsappcareersalesview,name="whatsupcareersalesview"),
    path('whatsupcareersales/', whatsappcareersales_view.as_view(), name="whatsupcareersales"),
    path('whatsupcareersalesedit/<int:id>', views.whatsappcareersalesedit, name="whatsupcareersalesedit"),
    path('whatsupcareersalescreate/', views.whatsappcareersalescreate, name="whatsupcareersalescreate"),
    #whatsapp bench sales
    path('whatsupbenchsalesview/<int:id>',views.whatsappbenchsalesview,name="whatsupbenchsalesview"),
    path('whatsupbenchsales/', whatsappbenchsales_view.as_view(), name="whatsupbenchsales"),
    path('whatsupbenchsalesedit/<int:id>', views.whatsappbenchsalesedit, name="whatsupbenchsalesedit"),
    path('whatsupbenchsalescreate/', views.whatsappbenchsalescreate, name="whatsupbenchsalescreate"),
    path('status/<int:id>/', views.status, name='status'),
    re_path(r'snippets/$', SnippetList.as_view(), name='snippet-list'),
    path('snippets/', SnippetList.as_view(), name="snippet"),
    path('customemailleadsfile/', views.customemailleadsfile, name='customemailleadsfile'),
    path('custombenchsalesfile/', views.custombenchsalesfile, name='custombenchsalesfile'),
    # path('locations/', views.locations, name="locations"),
    path('duplicatefilm/<int:id>/', views.duplicate_film, name='duplicatefilm'),
    path('emailduplicatefilm/<int:id>/', views.emailduplicate_film, name='emailduplicatefilm'),
    path('whatsappbenchsalescontent/<int:id>', views.whatsappbenchsalescontent, name="whatsappbenchsalescontent"),
    path('whatappspam/<str:string_param>/', views.spamremovals_testing, name="whatappspam"),
    path('whatappcareersales/<str:string_param>/', views.careersales_testing, name="whatappcareersales"),
    path('whatappbenchsales/<str:string_param>/', views.benchsales_testing, name="whatappbenchsales"),
    path('duplicated_emailleads/<int:id>/', DuplicatedCustomEmailleadsView.as_view(), name='duplicated_customemailleadsview'),
    path('whatsupduplicated_emailleads/<int:id>/', Duplicatedwhatsappcareersales_view.as_view(), name='duplicated_whatsupleadsview'),
    path('alias/',views.alias,name="alias"),
        
]

mysite/urls.py
from django.contrib import admin
from django.urls import  include, path
from django.conf import settings
from django.conf.urls.static import static
from core import views

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('chatgpt/', include('chatgpt.urls')),
    path('email/', include('mail.urls')),
    path('resume/', include('resume.urls')),
    path('contents/', include('contents.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms

from . models import whatsapp,Film, Emailbenchsales, Emailleadoppurtunities, Emailsample, Customleads, Custombench, CustomizeEmailLeads, CustomizeBenchsalesLeads, Customemailleads, Custombenchsales, DuplicatedFilm, DuplicatedCustomemailleads 
# import django_filters

class WhatsappForm(forms.ModelForm):
    class Meta:
        model = whatsapp
        fields = ('chat',)

class CustomizeEmailLeadsForm(forms.ModelForm):
    class Meta:
        model = CustomizeEmailLeads
        fields = ('Fileupload',)

class CustomizeBenchsalesLeadsForm(forms.ModelForm):
    class Meta:
        model = CustomizeBenchsalesLeads
        fields = ('BenchsalesFile',)

class FilmForm(forms.ModelForm):
    class Meta:
        model=Film
        fields="__all__"


# class EmailleadForm(forms.ModelForm):
#     class Meta:
#         model=Emaillead
#         fields="__all__"

class EmailbenchsalesForm(forms.ModelForm):
    class Meta:
        model=Emailbenchsales
        fields="__all__"

class CustomleadsForm(forms.ModelForm):
    class Meta:
        model=Customleads
        fields="__all__"


class EmailleadoppurtunitiesForm(forms.ModelForm):
    class Meta:
        model=Emailleadoppurtunities
        fields="__all__"

class EmailsampleForm(forms.ModelForm):
    class Meta:
        model=Emailsample
        fields="__all__"


class LocationChoiceField(forms.Form):

    locations = forms.ModelChoiceField(
        queryset=Film.objects.values_list("checkstatus", flat=True).distinct(),
        #empty_label=None
    )


class LabelChoiceField(forms.Form):

    label = forms.ModelChoiceField(
        queryset=Film.objects.values_list("dropdownlist", flat=True).distinct(),
        #empty_label=None
    )


class DateChoiceField(forms.Form):

    datesdata = forms.ModelChoiceField(
        queryset=Film.objects.values_list("title", flat=True).distinct(),
        #empty_label=None
    )

class UploadFileForm(forms.ModelForm):
    OPTION_CHOICES = (
        ('whatsapp', 'Whatsapp'),
        # ('email leads', 'Email Leads'),
        # ('email benchsales', 'Email Benchsales'),
        # ('email opportunities', 'Email Opportunities'),
    )
    option = forms.ChoiceField(choices=OPTION_CHOICES)

    class Meta:
        model = whatsapp
        fields = ('option', 'chat')
        # fields = "__all__"

# class EventFilterForm(forms.Form):
#     # date = forms.DateField()

#     def filter_events(self):
#         filtered_date = self.cleaned_data['title']
#         events = Film.objects.filter(date=filtered_date)
#         return events

class CustomemailleadsForm(forms.ModelForm):
    class Meta:
        model=Customemailleads
        fields="__all__"


class CustombenchsalesForm(forms.ModelForm):
    class Meta:
        model=Custombenchsales
        fields="__all__"

class CustombenchForm(forms.ModelForm):
    class Meta:
        model=Custombench
        fields="__all__"

class DuplicatedFilmForm(forms.ModelForm):
    class Meta:
        model=DuplicatedFilm
        fields="__all__"

class DuplicatedCustomemailleadsForm(forms.ModelForm):
    class Meta:
        model=DuplicatedCustomemailleads
        fields="__all__"

templates/delete.html


<!DOCTYPE html>
<html>
	<meta charset="utf-8">
    <title>delete</title>

	<style>
    body{
            margin: 0px;
            padding: 0px;
            font-family: system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue","Noto Sans","Liberation Sans",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
        }
		.deletediv {
			display: flex;
			justify-content: center;
			align-items: center;
			padding: 180px 0px;
		}
		.btns {
			border-radius: 20px;
            box-shadow: rgb(14 30 37 / 12%) 0px 2px 4px 0px, rgb(14 30 37 / 32%) 0px 2px 16px 0px ;
			padding: 20px;
		}
		.btns form h1 {
            margin: 0px;
			font-weight: normal;
		}
		.btns form p {
            text-align: center;
			font-size: 30px;
			font-weight: bold;
			margin: 0px;
		}
		.btn_grp {
			text-align: center;
			margin-top: 15px;
		}
		.btn_grp input {
			padding: 10px 20px;
            margin: 0px 5px;
            background: #f31027;
            color: #fff;
			border: none;
			border-radius: 10px;
			cursor: pointer;
		}
		.btn_grp a {
			padding: 10px 20px;
            margin: 0px 5px;
            background: #0d6efd;
            color: #fff;
			text-decoration: none;
			border: none;
			border-radius: 10px;
			cursor: pointer;
		}
	</style>
<body>	
<div class="deletediv">	
<div class="btns">
  <form method='POST'>
    {% csrf_token %}
	  <p>Delete</p>
    <h1>Are you sure you want to delete this item?</h1>
    <div class="btn_grp"><input type='submit' value='Yes' />
      <a class="btn btn-primary btn-sm" href="{% url 'retrieve' %}">Cancel</a>
    </div>
  </form>
</div>
</div>

</body>
</html>

templates/emailleadupload.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>whatsapp text File Upload</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <link rel="stylesheet" href="css/style.css"> -->
    <!-- CSS only -->
    <style>
      .button {
      position: relative;
      padding: 8px 16px;
      background: #0d6efd;
      border: none;
      outline: none;
      border-radius: 10px;
      cursor: pointer;
    }
    .top_header {
      background: #0b9b3f;
    }
    .button:active {
      background: #0d6efd;
    }
    
    .button__text {
      font: 20px;
      color: #ffffff;
      transition: all 0.2s;
    }
    
    .button--loading .button__text {
      visibility: hidden;
      opacity: 0;
    }
    .l_ogo {
      text-decoration: none;
      color: #fff;
      font-size: 23px;
    }
    .output_file {
      position: relative;
      padding: 8px 16px;
      margin-left: 10px;
      background: #0b9b3f;
      color: #fff;
      width: fit-content;
      border: none;
      outline: none;
      border-radius: 10px;
      text-decoration: none;
    }
    .output_file:hover {
      color: #fff;
    }
    .upbtn_filbtn {
      display: flex;
    }
    .upload_box {
      border: 1px solid #0b9b3f !important;
      box-shadow: rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px;
    }
    .button--loading::after {
      content: "";
      position: absolute;
      width: 16px;
      height: 16px;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      margin: auto;
      border: 4px solid transparent;
      border-top-color: #ffffff;
      border-radius: 50%;
      animation: button-loading-spinner 1s ease infinite;
    }
    
    @keyframes button-loading-spinner {
      from {
        transform: rotate(0turn);
      }
    
      to {
        transform: rotate(1turn);
      }
    }
    .down_lod {
      margin-left: 0px !important;
    }
    .output_file:hover {
      color: #fff;
    }
    .upbtn_filbtn {
      display: flex;
    }
    .cont {
      margin-top: 10px;
    }
    </style>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
    {% include 'header.html' %}
    <!-- <nav class="navbar navbar-expand-lg navbar-light header top_header">
      <a href="#" style="margin-left: 15px;" class="bace_title l_ogo"><i class="fa fa-commenting-o" aria-hidden="true"></i> Whatsapp  Groupchat Extractor</a>
    </nav> -->
    <div class="d-flex justify-content-center mt-5 upload_file_box">
      <div class="card upload_box p-3" style="width: 30rem;">
 
       
       {% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <!-- <button class="btn btn-primary upload_butons" type="submit">Upload</button> -->
    <div class="upbtn_filbtn">
      <button type="submit" class="button upload_butons" onclick="this.classList.toggle('button--loading')">
        <span class="button__text">Upload</span>
      </button>
      <!-- <a class="output_file" href="{{ '/media/media/data.csv' }}">Output File</a> -->
    </div>

  </form>

  <div>
    <p class="cont"> Sample CSV file for Email Benchsales</p>
    <a  class="output_file down_lod" href="{{ '/media/emailleads.csv' }}" download>Download</a>
  </div>
  <!-- <p></p> -->
  <!-- <a class="output_file" href="{{ '/media/media/data.csv' }}">output file</a> -->
  <!-- <p></p> -->
  
  <!-- <p>Uploaded files:</p> -->
  <!-- <ul>
    {% for obj in documents %}
      <li>
       
        <a href="{{ obj.document.url }}">{{ obj.document.name }}</a>
        <small>(Uploaded at: {{ obj.uploaded_at }})</small>
        <form method="POST" action="{% url 'delete_document' obj.id %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger btn-sm">Delete</button>
        </form> 
        <a href="" class="btn btn-danger btn-sm">Delete</a>
      </li>
    {% endfor %}
  </ul>  -->
{% endblock %}
    
    </div>
    </div>    

  
  </body>
</html>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

templates/search-yuvachages.html
<!DOCTYPE html>
<html>
<head>
    <title>Retrieve</title>
    <style>
        body{
            margin: 0px;
            padding: 0px;
            font-family: system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue","Noto Sans","Liberation Sans",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
        }
        .retrieve_table {
        margin-top: 20px;
    }
    .container {
        width: 90%;
        margin: auto;
    }
    table {
        /* * margin-left: 550px;
        margin-top: 150px; * */
        column-width: 20px;
        font-size: 15px;
        border: 5px solid black; 
        border: none;
        padding: 5px;
        border-collapse: collapse;
        /* width: 90%;
        margin: auto; */
    }
    thead {
        padding: 10px;
        background: #0b9b3f;
        color: #fff;
    }
    tr:nth-child(even){background-color: #ebe1ff}
    tbody {
        padding: 10px;
    }
    .retrieve_table th {
        border: none;
        
    }
    .editbtn {
        padding: 10px 20px;
        background: #0b9b3f;
        color: #fff;
        text-decoration: none;
        border-radius: 20px;
        font-size: 15px;
    }
    .deletebtn {
        padding: 10px 20px;
        background: #dc2626;
        color: #fff;
        text-decoration: none;
        border-radius: 20px;
        font-size: 15px;
    }
    .retrieve_table td {
       line-height: 25px;
    }
    .meg {
        display: inline-block;
        width: 200px;
        white-space: nowrap;
        overflow: hidden !important;
        text-overflow: ellipsis;
        border: none;
    }
    .top_btns {
        display: flex;
        justify-content: space-between;
        margin-top: 15px;
    }
    .btn_snippet {
        padding: 4px 15px;
        background: #0b9b3f;
        color: #fff;
        text-decoration: none;
        border-radius: 20px;
        font-size: 15px;
        border: none;
        cursor: pointer;
    }
    .btn_snippet:hover {
        background: #01471b;
    }
    .searc_h {
        padding: 4px 10px;
        border-radius: 15px;
        border: 1px solid #0b9b3f;
    }
    .searc_h_btn {
        padding: 4px 15px;
        background: #0b9b3f;
        color: #fff;
        text-decoration: none;
        border-radius: 20px;
        font-size: 15px;
        border: none;
        cursor: pointer;
    }
    .searc_h_btn:hover {
        background: #01471b;
    }
    .select_opt {
        padding: 4px 10px;
        border-radius: 15px;
        border: 1px solid #0b9b3f;
    }
    .submi_t_btn {
        padding: 4px 15px;
        background: #0b9b3f;
        color: #fff;
        text-decoration: none;
        border-radius: 20px;
        font-size: 15px;
        border: none;
        cursor: pointer;
    }
    .submi_t_btn:hover {
        background: #01471b;
    }
    </style>
    <!-- <script type="text/javascript">
        function searchdata(){
            var input,table,tr,td,filter,i;
            input = document.getElementById("searchdd1");
            filter = input.value;
            table = document.getElementById("table1");
            tr= table.getElementsByTagName("tr")
            for(i=0;i<tr.length;i++)
            {
                td=tr[i].getElementsByTagName("td")[500];
                if(td)
                {
                    displaydata = td.innertext;
                    if(displaydata.indexof(filter)>-1)
                    {
                        tr[i].style.display="";
                    }
                    else
                    {
                        tr[i].style.display="none";
                    }

                }
            }
        }
        function resettabledata();
        {
            location.load();
        }
    </script> -->
</head>

  <body>
    {% include 'header.html' %}
    <div class="container">
        <div class="top_btns">
          <form class="form-inline my-2 my-lg-0" >
            <input class="form-control mr-sm-2 searc_h" name="q" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0 searc_h_btn" type="submit">Search</button>
          </form>
          <!-- <div>
            <select id="searchdd1" onclick="searchdata();">
                <option disabled="true" selected>-----</option>
                <option value="0">0</option>
                <option value="1">1</option>
            </select>
            <input type="button" value="Reset Table" onclick=""/>
          </div> -->
          
            <!-- <form method="get" action="{% url 'search' %}">
                {{ location_list }} -->
                
                <!-- <label for="id_locations">Locations:</label><select name="locations" required="" id="id_locations">
                    <option value="" selected="">---------</option>
                  
                    <option value="1">1</option>
                  
                    <option value="0">0</option> -->
                <!-- <input type="submit" >
            </form> -->
            <form method="get" action="{% url 'search' %}">
                
                <!-- {{ label_list }} -->
                <label>Lead type</label>
                <select name="label" required="" id="id_label" class="select_opt">
                    <option value="" selected="">---------</option>
                  
                    <!-- <option value=""></option> -->
                  
                    <option value="Requirements">Requirements</option>
                  
                    <option value="Interview questions">Interview questions</option>
                  
                    <option value="Benchsales">Benchsales</option>
                  
                    <option value="Web content">Web content</option>
                  
                    <option value="Blog">Blog</option>
                  
                    <option value="Misc">Misc</option>
                  
                    <option value="Presentation">Presentation</option>
                  
                    <option value="Training">Training</option>
                  
                    <option value="3rd party Job posting &amp; Recruitment">3rd party Job posting &amp; Recruitment</option>
                  
                  </select>
                <input class="submi_t_btn" type="submit" >
            </form>
        </div>
          <!-- <div>
            <button type="submit" id="delete_btn" class="btn_delete">Delete</button>
        </div> -->
        
        <table class="retrieve_table" border="5px solid #000;">
            <tbody>
                <thead>
                    <tr>
                        <!-- <th width="15%"></th> -->
                        <th width="15%">Date and Time</th>
                        <th width="15%">Mobile Number</th>
                        <th width="50%">Message</th>
                        <!-- <th>status</th> -->
                        <th>Lead type</th>
                        <th width="10%">Edit</th>
                        <th width="10%">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- {%csrf_token %} -->
                    
                    {% for i in details %}
                    {% if i.checkstatus == 0 %}
                    
                    <tr>
                    <!-- <tr  id="{{i.id}}"> -->
                        <!-- <td><input type="checkbox" name="product_id[]" value="{{i.id}}" id="delete_product"></td> -->
                        <td style="padding:10px;">{{i.title}}</td>
                        <td style="padding:10px;">{{i.year}}</td>
                        <td style="padding:10px;">{{i.filmurl}}</td>
                        <!-- <td style="padding:10px;">{{i.checkstatus}}</td> -->
                        <td style="padding:10px;">{{i.dropdownlist}}</td>
                        <!-- <td style="padding:10px;" class="meg">{{i.genre}}</td> -->
                        <td style="padding:10px;text-align: center;"><a class="editbtn" href="{% url 'edit' i.pk %}">Edit</a></td>
                        <td style="padding:10px;text-align: center;"><a class="deletebtn" href="{% url 'delete' i.pk %}">Delete</a></td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </tbody>
        </table>
        <!-- <div>
            <button type="submit" id="delete_btn" class="btn_delete">Delete</button>
        </div> -->
    </div>
    <!-- <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script>
        $(document).ready(function(){
            $('#delete_btn').click(function(){
                if(confirm("Are you sure you want to delete this items ?")){
                    var id =[];
                    var csrf=$('input[name=csrfmiddlewaretoken').val();
                    $(':checkbox:checked').each(function(i){
                        id[i]=$(this).val()
                    })
                    if(id.length===0){
                        alert("please select item to delete ?")
                    }else{
                        console.log(id)
                        $.ajax({
                            url:'.',
                            method:"POST",
                            data:{
                                id,
                                csrfmiddlewaretoken:csrf
                            },
                            success:function(response){
                                for(var i=0; i < id.length; i++){
                                $('tr#'+id[i]+'').css('background-color', '#ccc');
                                $('tr#'+id[i]+'').fadeOut('slow');
                            }                               
                            }
                        })
                    }                  
                }
            })
        })
    </script> -->

</body>

</html>