contents/urls.py
from django.urls import path

from . import views
from contents.views import (CustomWebcontent_view, Customblog_view)


urlpatterns = [
    path("", views.index, name="index"),
    path('customwebcontentsfile/', views.customwebcontentsfile, name='customwebcontentsfile'),
    path('customwebcontentleads/',CustomWebcontent_view.as_view(),name="customwebcontentleads"),
    path('customwebcontentview/<int:id>',views.Customwebcontentview, name="customwebcontentview"),
    path('blogfile/', views.blogfile, name='blogfile'),
    path('blog/',Customblog_view.as_view(),name="blog"),
    path('blogview/<int:id>',views.blogview,name="blogview"),
    path('documentationuploads/', views.documentationuploads, name="documentationuploads"),
]

core/urls.py
from django.urls import path 
from  . import views 
from core.views import (Product_view, SnippetList, Leads_view, Emailopp_view, Emailsamplelead_view, Emailbenchsales_view, CustomEmailleads_view, CustomBenchsales_view, CustomEmailleadsopportunities_view, whatsappcareersales_view, whatsappbenchsales_view, DuplicatedCustomEmailleadsView,Duplicatedwhatsappcareersales_view)

from django.urls import re_path
urlpatterns = [
    path('index/',views.index, name='index'),
    path('getDatapoint/',views.getDatapoint, name='getDatapoint'),
    path('upload/', views.upload_txt, name='upload_txt'),
    path('emailleadupload/', views.emaillead_upload_txt, name='emailleadupload'),
    path('emailbenchsalesupload/', views.emailbenchsalesupload, name='emailbenchsalesupload'),
    path('emailbenchsalesupdate/<int:id>',views.benchsalesupdate,name="emailbenchsalesupdate"),
    path('emailbenchsalesedit/<int:id>',views.emailbenchsalesedit,name="emailbenchsalesedit"),
    path('benchsales/', Emailbenchsales_view.as_view(), name="benchsales"),
    #cutom email leads
    path('customemailleadsupdate/<int:id>',views.customemailleadsupdate,name="customemailleadsupdate"),
    path('customemailleadsview/<int:id>',views.customemailleadsedit,name="customemailleadsview"),
    path('customemailleads/',CustomEmailleads_view.as_view(),name="customemailleads"),
    path('customemailleadscreate/', views.Customemailleadscreate, name="customemailleadscreate"),
    path('customemailleadsedits/<int:id>', views.customemailleadsedits, name="customemailleadsedits"),
    path('customemailleadcontent/<int:id>', views.customemailleadcontent, name="customemailleadcontent"),
    path('customemailleadsupdateadd/<int:id>', views.customemailleadsupdateadd, name="customemailleadsupdateadd"),
    # custom email leads oppurtunties
    path('customemailleadsopportunities/',CustomEmailleadsopportunities_view.as_view(),name="customemailleadsopportunities"),
    path('customleadopportunitiesview/<int:id>', views.customleadopportunitiesview, name="customleadopportunitiesview"),

    # custom email bench sales 
    path('custombenchsalesedits/<int:id>',views.custombenchsalesedits, name="custombenchsalesedits" ),
    path('custombenchsalesupdateadd/<int:id>', views.custombenchsalesupdateadd, name="custombenchsalesupdateadd"),

    path('custombenchsalescontent/<int:id>', views.custombenchsalescontent, name="custombenchsalescontent"),
    path('custombenchsalesupdate/<int:id>',views.custombenchsalesupdate,name="custombenchsalesupdate"),
    path('custombenchsalesview/<int:id>',views.custombenchsalesedit,name="custombenchsalesview"),
    path('custombenchsales/',CustomBenchsales_view.as_view(),name="custombenchsales"),
    path('Custombenchsalescreate/', views.Custombenchsalescreate, name="Custombenchsalescreate"),
    
    path('custombenchsalesadd/', views.custombenchsalesadd, name="custombenchsalesadd"),
    # path('', views.upload_txt, name='upload_txt'),
    # path('retrieve/',views.retrieve,name="retrieve"),
    path('edit/<int:id>',views.edit,name="edit"),
    path('leadedit/<int:id>',views.leadedit,name="leadedit"),
    path('emailnewleadsedit/<int:id>',views.emailsampleleadedit,name="emailnewleadsedit"),
    # path('emailleadedit/<int:id>',views.emailleadedit,name="emailleadedit"),
    path('emailleadoppurtunitiesedit/<int:id>',views.emailleadoppurtunitiesedit,name="emailleadoppurtunitiesedit"),
    path('update/<int:id>',views.update,name="update"),
    path('emailnewleadsupdate/<int:id>',views.sampleleadupdate,name="emailnewleadsupdate"),
    # path('emailleadupdate/<int:id>',views.emailleadupdate,name="emailleadupdate"),
    path('emailleadoppupdate/<int:id>',views.emailleadoppupdate,name="emailleadoppupdate"),
    path('leadupdate/<int:id>',views.leadupdate,name="leadupdate"),
    # path('leadupdate/<int:id>',views.emailleadoppupdate,name="leadupdate"),
    path('delete/<int:id>',views.delete,name="delete"),
    path('opportunities/',views.search, name="search"),
    path('', Product_view.as_view(), name="home"),
    # path('emailhome/', Emailproduct_view.as_view(), name="emailhome"),
    path('emailleadoppurtunities/', Emailopp_view.as_view(), name="emailleadoppurtunities"),
    path('emailnewleads/', Emailsamplelead_view.as_view(), name="emailnewleads"),
    path('retrieve/', Product_view.as_view(), name="retrieve"),
    path('leads/', Leads_view.as_view(), name="leads"),
    #whatsapp career sales
    path('whatsupcareersalesview/<int:id>',views.whatsappcareersalesview,name="whatsupcareersalesview"),
    path('whatsupcareersales/', whatsappcareersales_view.as_view(), name="whatsupcareersales"),
    path('whatsupcareersalesedit/<int:id>', views.whatsappcareersalesedit, name="whatsupcareersalesedit"),
    path('whatsupcareersalescreate/', views.whatsappcareersalescreate, name="whatsupcareersalescreate"),
    #whatsapp bench sales
    path('whatsupbenchsalesview/<int:id>',views.whatsappbenchsalesview,name="whatsupbenchsalesview"),
    path('whatsupbenchsales/', whatsappbenchsales_view.as_view(), name="whatsupbenchsales"),
    path('whatsupbenchsalesedit/<int:id>', views.whatsappbenchsalesedit, name="whatsupbenchsalesedit"),
    path('whatsupbenchsalescreate/', views.whatsappbenchsalescreate, name="whatsupbenchsalescreate"),
    path('status/<int:id>/', views.status, name='status'),
    re_path(r'snippets/$', SnippetList.as_view(), name='snippet-list'),
    path('snippets/', SnippetList.as_view(), name="snippet"),
    path('customemailleadsfile/', views.customemailleadsfile, name='customemailleadsfile'),
    path('custombenchsalesfile/', views.custombenchsalesfile, name='custombenchsalesfile'),
    # path('locations/', views.locations, name="locations"),
    path('duplicatefilm/<int:id>/', views.duplicate_film, name='duplicatefilm'),
    path('emailduplicatefilm/<int:id>/', views.emailduplicate_film, name='emailduplicatefilm'),
    path('whatsappbenchsalescontent/<int:id>', views.whatsappbenchsalescontent, name="whatsappbenchsalescontent"),
    path('whatappspam/<str:string_param>/', views.spamremovals_testing, name="whatappspam"),
    path('whatappcareersales/<str:string_param>/', views.careersales_testing, name="whatappcareersales"),
    path('whatappbenchsales/<str:string_param>/', views.benchsales_testing, name="whatappbenchsales"),
    path('duplicated_emailleads/<int:id>/', DuplicatedCustomEmailleadsView.as_view(), name='duplicated_customemailleadsview'),
    path('whatsupduplicated_emailleads/<int:id>/', Duplicatedwhatsappcareersales_view.as_view(), name='duplicated_whatsupleadsview'),
    path('alias/',views.alias,name="alias"),
        
]

mysite/urls.py
from django.contrib import admin
from django.urls import  include, path
from django.conf import settings
from django.conf.urls.static import static
from core import views

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('chatgpt/', include('chatgpt.urls')),
    path('email/', include('mail.urls')),
    path('resume/', include('resume.urls')),
    path('contents/', include('contents.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contents/models.py
from django.db import models

# Create your models here.
class Customwebcontent(models.Model):
    webtodaysdate = models.TextField(blank=True)
    webSubject = models.TextField(blank=True)
    webFrom = models.TextField(blank=True)
    webReceived_Time = models.TextField(blank=True)
    webEmail_Body = models.TextField(blank=True)
    webEmail_Bodyhtml = models.TextField(blank=True)
    webcheckstatus = models.PositiveSmallIntegerField(default=1)
    # dropdownlist = models.TextField(default="New")

    
    def __str__(self, *args, **kwargs):
        return self.webSubject
    
class blogbenchsales(models.Model):
    blogtodaysdate = models.TextField(blank=True)
    blogSubject = models.TextField(blank=True)
    blogFrom = models.TextField(blank=True)
    blogReceived_Time = models.TextField(blank=True)
    blogEmail_Body = models.TextField(blank=True)
    blogEmail_Bodyhtml = models.TextField(blank=True)
    blogcheckstatus = models.PositiveSmallIntegerField(default=1)
    # dropdownlist = models.TextField(default="New")

    
    def __str__(self, *args, **kwargs):
        return self.blogSubject
    

contents/forms.py
from django import forms

from . models import Customwebcontent, blogbenchsales
# import django_filters

class CustomwebcontentForm(forms.ModelForm):
    class Meta:
        model = Customwebcontent
        fields = '__all__'

class blogbenchsalesForm(forms.ModelForm):
    class Meta:
        model=blogbenchsales
        fields="__all__"

core/forms.py
from django import forms

from . models import whatsapp,Film, Emailbenchsales, Emailleadoppurtunities, Emailsample, Customleads, Custombench, CustomizeEmailLeads, CustomizeBenchsalesLeads, Customemailleads, Custombenchsales, DuplicatedFilm, DuplicatedCustomemailleads 
# import django_filters

class WhatsappForm(forms.ModelForm):
    class Meta:
        model = whatsapp
        fields = ('chat',)

class CustomizeEmailLeadsForm(forms.ModelForm):
    class Meta:
        model = CustomizeEmailLeads
        fields = ('Fileupload',)

class CustomizeBenchsalesLeadsForm(forms.ModelForm):
    class Meta:
        model = CustomizeBenchsalesLeads
        fields = ('BenchsalesFile',)

class FilmForm(forms.ModelForm):
    class Meta:
        model=Film
        fields="__all__"


# class EmailleadForm(forms.ModelForm):
#     class Meta:
#         model=Emaillead
#         fields="__all__"

class EmailbenchsalesForm(forms.ModelForm):
    class Meta:
        model=Emailbenchsales
        fields="__all__"

class CustomleadsForm(forms.ModelForm):
    class Meta:
        model=Customleads
        fields="__all__"


class EmailleadoppurtunitiesForm(forms.ModelForm):
    class Meta:
        model=Emailleadoppurtunities
        fields="__all__"

class EmailsampleForm(forms.ModelForm):
    class Meta:
        model=Emailsample
        fields="__all__"


class LocationChoiceField(forms.Form):

    locations = forms.ModelChoiceField(
        queryset=Film.objects.values_list("checkstatus", flat=True).distinct(),
        #empty_label=None
    )


class LabelChoiceField(forms.Form):

    label = forms.ModelChoiceField(
        queryset=Film.objects.values_list("dropdownlist", flat=True).distinct(),
        #empty_label=None
    )


class DateChoiceField(forms.Form):

    datesdata = forms.ModelChoiceField(
        queryset=Film.objects.values_list("title", flat=True).distinct(),
        #empty_label=None
    )

class UploadFileForm(forms.ModelForm):
    OPTION_CHOICES = (
        ('whatsapp', 'Whatsapp'),
        # ('email leads', 'Email Leads'),
        # ('email benchsales', 'Email Benchsales'),
        # ('email opportunities', 'Email Opportunities'),
    )
    option = forms.ChoiceField(choices=OPTION_CHOICES)

    class Meta:
        model = whatsapp
        fields = ('option', 'chat')
        # fields = "__all__"

# class EventFilterForm(forms.Form):
#     # date = forms.DateField()

#     def filter_events(self):
#         filtered_date = self.cleaned_data['title']
#         events = Film.objects.filter(date=filtered_date)
#         return events

class CustomemailleadsForm(forms.ModelForm):
    class Meta:
        model=Customemailleads
        fields="__all__"


class CustombenchsalesForm(forms.ModelForm):
    class Meta:
        model=Custombenchsales
        fields="__all__"

class CustombenchForm(forms.ModelForm):
    class Meta:
        model=Custombench
        fields="__all__"

class DuplicatedFilmForm(forms.ModelForm):
    class Meta:
        model=DuplicatedFilm
        fields="__all__"

class DuplicatedCustomemailleadsForm(forms.ModelForm):
    class Meta:
        model=DuplicatedCustomemailleads
        fields="__all__"

templates/contents/upload_document.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>whatsapp Documentation File Upload</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <link rel="stylesheet" href="css/style.css"> -->
    <!-- CSS only -->
    <style>
      .button {
      position: relative;
      padding: 8px 16px;
      background: #0d6efd;
      border: none;
      outline: none;
      border-radius: 10px;
      cursor: pointer;
    }
    .top_header {
      background: #0b9b3f;
    }
    .button:active {
      background: #0d6efd;
    }
    
    .button__text {
      font: 20px;
      color: #ffffff;
      transition: all 0.2s;
    }
    
    .button--loading .button__text {
      visibility: hidden;
      opacity: 0;
    }
    .l_ogo {
      text-decoration: none;
      color: #fff;
      font-size: 23px;
    }
    .output_file {
      position: relative;
      padding: 8px 16px;
      margin-left: 10px;
      background: #0b9b3f;
      color: #fff;
      width: fit-content;
      border: none;
      outline: none;
      border-radius: 10px;
      text-decoration: none;
    }
    .down_lod {
      margin-left: 0px !important;
    }
    .output_file:hover {
      color: #fff;
    }
    .upbtn_filbtn {
      display: flex;
    }
    .upload_box {
      border: 1px solid #0b9b3f !important;
      box-shadow: rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px;
    }
    .button--loading::after {
      content: "";
      position: absolute;
      width: 16px;
      height: 16px;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      margin: auto;
      border: 4px solid transparent;
      border-top-color: #ffffff;
      border-radius: 50%;
      animation: button-loading-spinner 1s ease infinite;
    }
    #id_option {
      padding: 3px 10px;
      border-radius: 15px;
    }
    
    @keyframes button-loading-spinner {
      from {
        transform: rotate(0turn);
      }
    
      to {
        transform: rotate(1turn);
      }
    }
    .cont {
      margin-top: 10px;
    }
    </style>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
    {% include 'header.html' %}
    <!-- <nav class="navbar navbar-expand-lg navbar-light header top_header">
      <a href="#" style="margin-left: 15px;" class="bace_title l_ogo"><i class="fa fa-commenting-o" aria-hidden="true"></i> Whatsapp  Groupchat Extractor</a>
    </nav> -->
    <div class="d-flex justify-content-center mt-5 upload_file_box">
      <div class="card upload_box p-3" style="width: 30rem;">
        <h2 style="margin-bottom: 20px;">Documentations upload</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <span style="margin-bottom: 20px;">{{errortext}}</span>
            <input type="file" name="myfile">
            <!-- <input type="submit" value="Upload"> -->
            <button type="submit" class="button upload_butons" >
                <span class="button__text">Upload</span>
            </button>
        </form>

    
    </div>
    </div>    

  
  </body>
</html>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

templates/contents/upload_document1.html
<!DOCTYPE html>
<html>
<head>
    <title>Upload Document</title>
</head>
<body>
    <h2>Upload a Document</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="myfile">
        <input type="submit" value="Upload">
    </form>
</body>
</html>